name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Update Config in HTML
        run: |
          # First, verify that secrets are available
          if [ -z "${{ secrets.TURN_URL_GOLDI }}" ]; then
            echo "Warning: Using fallback STUN/TURN configuration"
            # Use public Google STUN servers if secrets aren't set
            sed -i 's|// Default public STUN server|// Using fallback configuration|' index.html
          else
            # Escape URLs properly for sed
            STUN_GOLDI=$(echo "${{ secrets.STUN_URL_GOLDI }}" | sed 's/[\/&]/\\&/g')
            STUN_GOOGLE=$(echo "${{ secrets.STUN_URL_GOOGLE }}" | sed 's/[\/&]/\\&/g')
            STUN_METERED=$(echo "${{ secrets.STUN_URL_METERED }}" | sed 's/[\/&]/\\&/g')
            TURN_GOLDI=$(echo "${{ secrets.TURN_URL_GOLDI }}" | sed 's/[\/&]/\\&/g')
            
            # Update the configuration
            sed -i "s|stun:stun.l.google.com:19302|${STUN_GOLDI}|g" index.html
            sed -i "s|stun:stun1.l.google.com:19302|${STUN_GOOGLE}|g" index.html
            sed -i "s|stun:stun2.l.google.com:19302|${STUN_METERED}|g" index.html
            sed -i "s|stun:stun.relay.metered.ca:80|${TURN_GOLDI}|g" index.html
            sed -i "s|\"anonymous\"|\"${{ secrets.TURN_USERNAME }}\"|g" index.html
            sed -i "s|\"anonymous\"|\"${{ secrets.TURN_CREDENTIAL }}\"|g" index.html
          fi
          
          # Verify the substitution
          echo "Checking configuration (with credentials redacted)..."
          grep -A 10 "window.CONFIG = {" index.html | sed 's/credential: ".*"/credential: "REDACTED"/'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
